### PR TITLE
Add example for including in Docker using specific version

### PR DESCRIPTION
**Pull request by ErikSchierboom**

### CODE REVIEW

**Review by neenjaw — APPROVED** [review]

**Comment by neenjaw** [comment]
Oops, I didn't mean to approve this, I was just clicking to read it.  ack!

**Comment by neenjaw** [comment]
(though it does look good to me)

**Comment by ErikSchierboom** [comment]
I'll just merge it then :)

**Comment by iHiD** [comment]
Nice. Thanks 🙂 

Did you solve the building locally issue, @ErikSchierboom. It would be nice if there was docs for how to work with a local version too if so.

**Comment by ErikSchierboom** [comment]
@iHiD I've created [an issue](https://github.com/exercism/tooling-webserver/issues/20).

**Pull request merged**
